# Generated by Django 5.0.3 on 2024-03-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('idevento', models.CharField(primary_key=True, serialize=False)),
                ('txnomeevento', models.CharField(max_length=128)),
                ('txdescricaoevento', models.CharField(max_length=512, null=True)),
                ('dtinicialevento', models.DateField()),
                ('dtfinalevento', models.DateField()),
                ('hrinicialevento', models.TimeField()),
                ('hrfinalevento', models.TimeField()),
                ('numinimoparticipante', models.IntegerField(null=True)),
                ('numaximoparticipante', models.IntegerField(null=True)),
                ('nuparticipantes', models.IntegerField()),
                ('vlinscricaoevento', models.DecimalField(decimal_places=8, max_digits=10)),
                ('txlocalevento', models.TextField()),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
    ]
