# Generated by Django 5.0.3 on 2024-03-24 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='organizer',
            fields=[
                ('idorganizador', models.CharField(primary_key=True, serialize=False, verbose_name='idorganizador')),
                ('txcpforganizador', models.CharField(max_length=14, verbose_name='txcpforganizador')),
                ('txnomeorganizador', models.CharField(max_length=256, verbose_name='txnomeorganizador')),
                ('txsenhaorganizador', models.CharField(max_length=10, verbose_name='txsenhaorganizador')),
                ('txemailorganizador', models.CharField(max_length=256, verbose_name='txemailorganizador')),
                ('dtnascimentoorganizador', models.DateField(verbose_name='dtnascimentoorganizador')),
                ('eventoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.events')),
            ],
            options={
                'db_table': 'organizer',
                'managed': True,
            },
        ),
    ]
