# Generated by Django 5.0.3 on 2024-03-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='participant',
            fields=[
                ('idparticipante', models.AutoField(primary_key=True, serialize=False, verbose_name='idparticipante')),
                ('txcpfparticipante', models.CharField(max_length=14, verbose_name='txcpfparticipante')),
                ('txnomeparticipante', models.CharField(max_length=256, verbose_name='txnomeparticipante')),
                ('txsenhaparticipante', models.CharField(max_length=10, verbose_name='txsenhaparticipante')),
                ('txemailparticipante', models.CharField(max_length=256, verbose_name='txemailparticipante')),
                ('dtnascparticipante', models.DateField(verbose_name='dtnascparticipante')),
            ],
            options={
                'db_table': 'participant',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='events',
            name='dtfinalevento',
            field=models.DateField(verbose_name='dtfinalevento'),
        ),
        migrations.AlterField(
            model_name='events',
            name='dtinicialevento',
            field=models.DateField(verbose_name='dtinicialevento'),
        ),
        migrations.AlterField(
            model_name='events',
            name='hrfinalevento',
            field=models.TimeField(verbose_name='hrfinalevento'),
        ),
        migrations.AlterField(
            model_name='events',
            name='hrinicialevento',
            field=models.TimeField(verbose_name='hrinicialevento'),
        ),
        migrations.AlterField(
            model_name='events',
            name='idevento',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='idevento'),
        ),
        migrations.AlterField(
            model_name='events',
            name='numaximoparticipante',
            field=models.IntegerField(null=True, verbose_name='numaximoparticipante'),
        ),
        migrations.AlterField(
            model_name='events',
            name='numinimoparticipante',
            field=models.IntegerField(null=True, verbose_name='numinimoparticipante'),
        ),
        migrations.AlterField(
            model_name='events',
            name='nuparticipantes',
            field=models.IntegerField(verbose_name='nuparticipantes'),
        ),
        migrations.AlterField(
            model_name='events',
            name='txdescricaoevento',
            field=models.CharField(max_length=512, null=True, verbose_name='txdescricaoevento'),
        ),
        migrations.AlterField(
            model_name='events',
            name='txlocalevento',
            field=models.TextField(verbose_name='txlocalevento'),
        ),
        migrations.AlterField(
            model_name='events',
            name='txnomeevento',
            field=models.CharField(max_length=128, verbose_name='txnomeevento'),
        ),
        migrations.AlterField(
            model_name='events',
            name='vlinscricaoevento',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='vlinscricaoevento'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='idorganizador',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='idorganizador'),
        ),
    ]
