# Generated by Django 5.0.3 on 2024-03-26 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_participant_alter_events_dtfinalevento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='participants_events',
            fields=[
                ('idpresenca', models.AutoField(primary_key=True, serialize=False, verbose_name='idpresenca')),
                ('presenca', models.BooleanField(verbose_name='presenca')),
                ('eventoid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.events')),
                ('participanteid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.participant')),
            ],
            options={
                'db_table': 'participants_events',
                'managed': True,
            },
        ),
    ]
